[build]: pnpm 및 webpack 초기 세팅 중
f-lab-edu/smart-calendar pull request #1
Opened 2023-05-14 04:49 UTC by rlaqudwls25

2023-05-16 06:36 UTC, f-lab-kevin requested changes

2023-05-16 06:36 UTC, f-lab-kevin commented on webpack.dev.js
> +module.export = merge(common, {
module.export 키워드를 보면 s가 빠진것을 알수가 있습니다
merge 동작이 정상적으로 이루어지지 않기 때문에 발생하는 문제에요

코드를 작성할 때 키워드 하나하나 정확하게 쓰고 계신지 꼼꼼히 확인해주시면 좋을 것 같아요

2023-05-16 06:36 UTC, f-lab-kevin commented on webpack.prod.js
> +module.export = merge(common, {
여기도 s가 빠져있네요

2023-05-16 06:36 UTC, f-lab-kevin commented on webpack.common.js
> +        test: /\\.tsx?$/,
\\ 두개를 작성하진 이유가 있을까요?

2023-05-16 06:36 UTC, f-lab-kevin commented on webpack.common.js
> +    filename: 'bundle.js',
cleanup 플러그인을 사용하기 때문에 파일은 교체될 순 있지만 이름이 같아 네트워크 관점에서 캐싱이 될 우려가 있습니다.

hash값을 적용하여 새로 빌드가 되었을 때 캐싱파일을 사용하지 않도록 output 설정값을 바꾸는게 나을것 같아요

2023-05-16 06:36 UTC, f-lab-kevin commented on tsconfig.json
> +  }
include, exclude 프로퍼티를 적용해서 트랜스파일링이 되는 대상을 명시적으로 표현하면 좋을 것 같아요

2023-05-16 06:36 UTC, f-lab-kevin commented on webpack.common.js
> +  entry: './index.tsx',
경로가 잘못설정되어 있습니다

2023-05-16 06:39 UTC, f-lab-kevin commented
추가로 피드백을 드리자면
1. 브랜치 이름은 되도록 영문으로 작성해주세요. 간혹 unicode로 한글이 출력되기때문에 브랜치명을 볼 때 명시적이지 않을수도 있어요
2. PR등록 시 작업한 내용에 대해 설명해주세요. 추가로 PR 템플릿은 어떤 내용이 들어가면 좋을지 생각해보시면서 template 파일을 만들고 적용해보시는 것도 좋을 것 같아요

2023-05-16 13:09 UTC, rlaqudwls25 commented on webpack.common.js
> +  entry: './index.tsx',
@f-lab-kevin 
이 문제인가 싶어서 ./src/index.tsx로 수정하고 진행했는데도 error가 계속 떳었습니다..

2023-05-16 13:10 UTC, rlaqudwls25 commented on webpack.common.js
> +        test: /\\.tsx?$/,
@f-lab-kevin
오타여서  수정했습니다~

2023-05-16 13:21 UTC, rlaqudwls25 commented on webpack.dev.js
> +module.export = merge(common, {
😢 네..

2023-05-16 13:22 UTC, rlaqudwls25 commented on webpack.prod.js
> +module.export = merge(common, {
😢 네,,

2023-05-16 14:34 UTC, rlaqudwls25 commented on tsconfig.json
> +  }
@f-lab-kevin 
```
"include": ["src"],
"exclude": ["node_modules"]
```
* include 및 exclude를 명시적으로 표현했는데, include와 exclude를 명시적으로 표현하지 않아도 기본적으로 설정되는 값이 있어도 이렇게 따로 설정을 해주는게 좋은건가요? 
* wildcard를 설정하지 않아도 하위 디렉토리에 .ts .tsx .d.ts 파일을 다 지원해주기 때문에 `src` 와 `src/**/*`는 같은 의미인거 같아서 일단 src로 지정해주었습니다.(혹시 틀린 부분이면 말씀해주세여!)

참고 링크: https://www.typescriptlang.org/tsconfig#exclude

2023-05-16 14:47 UTC, rlaqudwls25 commented on webpack.common.js
> +    filename: 'bundle.js',
@f-lab-kevin 이 부분은 아직 더 찾아보고 있습니다~

2023-05-17 16:25 UTC, f-lab-kevin commented on webpack.common.js
> +    filename: 'bundle.js',
@rlaqudwls25 https://webpack.js.org/configuration/output/#outputfilename
여기 참고해보시면 될거같아요~

2023-05-17 16:25 UTC, f-lab-kevin commented on webpack.common.js
> +  entry: './index.tsx',
어떤 에러가 발생하고 있나요? @rlaqudwls25

2023-05-18 04:23 UTC, f-lab-kevin commented
react-query recoil 초기 설정은 다음단계에 진행하실 예정이신가요?

2023-05-18 13:18 UTC, f-lab-kevin approved these changes
고생하셨습니다 👍

2023-05-18 13:20 UTC, merged